### 限流接口
GET http://127.0.0.1:8080/flow?name=dazuo&age=22
### 降级接口
GET http://127.0.0.1:8080/degrade

### easy-mock
GET https://www.easy-mock.com/mock/5aceff1900a2457ce2e505e6/example/user

### zxcity-restful
POST http://127.0.0.1:8080/zxcity_restful/ws/rest
Content-Type: application/x-www-form-urlencoded
apikey: test

cmd=shop/findTradingGiftList&data={"orderId":1}&version=1

###