### easy-mock
GET https://www.easy-mock.com/mock/5aceff1900a2457ce2e505e6/example/user

### dubbo接口
POST http://127.0.0.1:8080/zxcity_restful/ws/rest
Content-Type: application/x-www-form-urlencoded
apikey: test

cmd=shop/findTradingGiftList&data={"orderId":1}&version=1

### 流控接口
POST http://127.0.0.1:8080/zxcity_restful/ws/rest
Content-Type: application/x-www-form-urlencoded
apikey: test

cmd=shop/flow&data={}&version=1

### 降级接口
POST http://127.0.0.1:8080/zxcity_restful/ws/rest
Content-Type: application/x-www-form-urlencoded
apikey: test

cmd=shop/degrade&data={}&version=1

###
