// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message-payload.proto

package com.maxzuo.netty.hello.protocol;

public interface MessagePayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessagePayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string content = 2;</code>
   */
  String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int32 type = 3;</code>
   */
  int getType();

  /**
   * <code>string time = 4;</code>
   */
  String getTime();
  /**
   * <code>string time = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
