// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message-payload.proto

package com.maxzuo.netty.hello.protocol;

public final class NetworkProtocol {
  private NetworkProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessagePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessagePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025message-payload.proto\"I\n\016MessagePayloa" +
      "d\022\n\n\002id\030\001 \001(\005\022\017\n\007content\030\002 \001(\t\022\014\n\004type\030\003" +
      " \001(\005\022\014\n\004time\030\004 \001(\tB.\n\031com.maxzuo.proto.p" +
      "rotocolB\017NetworkProtocolP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MessagePayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessagePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessagePayload_descriptor,
        new String[] { "Id", "Content", "Type", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
