// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message-entity.proto

package com.maxzuo.protobuf;

public final class NetworkEntity {
  private NetworkEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>bytes msg = 3;</code>
     * @return The msg.
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public  static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      name_ = "";
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employee();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {

              msg_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetworkEntity.internal_static_Employee_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetworkEntity.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Employee.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>bytes msg = 3;</code>
     * @return The msg.
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!msg_.isEmpty()) {
        output.writeBytes(3, msg_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Employee)) {
        return super.equals(obj);
      }
      Employee other = (Employee) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetworkEntity.internal_static_Employee_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetworkEntity.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Employee.class, Builder.class);
      }

      // Construct using com.maxzuo.protobuf.NetworkEntity.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        msg_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetworkEntity.internal_static_Employee_descriptor;
      }

      @Override
      public Employee getDefaultInstanceForType() {
        return Employee.getDefaultInstance();
      }

      @Override
      public Employee build() {
        Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Employee buildPartial() {
        Employee result = new Employee(this);
        result.name_ = name_;
        result.age_ = age_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Employee) {
          return mergeFrom((Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Employee other) {
        if (other == Employee.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getMsg() != com.google.protobuf.ByteString.EMPTY) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msg = 3;</code>
       * @return The msg.
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>bytes msg = 3;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Employee();
    }

    public static Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @Override
    public Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CompanyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Company)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string summary = 2;</code>
     * @return The summary.
     */
    String getSummary();
    /**
     * <code>string summary = 2;</code>
     * @return The bytes for summary.
     */
    com.google.protobuf.ByteString
        getSummaryBytes();

    /**
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>string time = 4;</code>
     * @return The time.
     */
    String getTime();
    /**
     * <code>string time = 4;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    java.util.List<Employee>
        getEmployeesList();
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    Employee getEmployees(int index);
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    int getEmployeesCount();
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    java.util.List<? extends EmployeeOrBuilder>
        getEmployeesOrBuilderList();
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    EmployeeOrBuilder getEmployeesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Company}
   */
  public  static final class Company extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Company)
      CompanyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Company.newBuilder() to construct.
    private Company(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Company() {
      summary_ = "";
      time_ = "";
      employees_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Company();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Company(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              summary_ = s;
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                employees_ = new java.util.ArrayList<Employee>();
                mutable_bitField0_ |= 0x00000001;
              }
              employees_.add(
                  input.readMessage(Employee.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          employees_ = java.util.Collections.unmodifiableList(employees_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetworkEntity.internal_static_Company_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetworkEntity.internal_static_Company_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Company.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int SUMMARY_FIELD_NUMBER = 2;
    private volatile Object summary_;
    /**
     * <code>string summary = 2;</code>
     * @return The summary.
     */
    public String getSummary() {
      Object ref = summary_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      }
    }
    /**
     * <code>string summary = 2;</code>
     * @return The bytes for summary.
     */
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private volatile Object time_;
    /**
     * <code>string time = 4;</code>
     * @return The time.
     */
    public String getTime() {
      Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 4;</code>
     * @return The bytes for time.
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMPLOYEES_FIELD_NUMBER = 5;
    private java.util.List<Employee> employees_;
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    public java.util.List<Employee> getEmployeesList() {
      return employees_;
    }
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    public java.util.List<? extends EmployeeOrBuilder>
        getEmployeesOrBuilderList() {
      return employees_;
    }
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    public int getEmployeesCount() {
      return employees_.size();
    }
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    public Employee getEmployees(int index) {
      return employees_.get(index);
    }
    /**
     * <code>repeated .Employee employees = 5;</code>
     */
    public EmployeeOrBuilder getEmployeesOrBuilder(
        int index) {
      return employees_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getSummaryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, summary_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, time_);
      }
      for (int i = 0; i < employees_.size(); i++) {
        output.writeMessage(5, employees_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getSummaryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, summary_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, time_);
      }
      for (int i = 0; i < employees_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, employees_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Company)) {
        return super.equals(obj);
      }
      Company other = (Company) obj;

      if (getId()
          != other.getId()) return false;
      if (!getSummary()
          .equals(other.getSummary())) return false;
      if (getType()
          != other.getType()) return false;
      if (!getTime()
          .equals(other.getTime())) return false;
      if (!getEmployeesList()
          .equals(other.getEmployeesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getSummary().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      if (getEmployeesCount() > 0) {
        hash = (37 * hash) + EMPLOYEES_FIELD_NUMBER;
        hash = (53 * hash) + getEmployeesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Company parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Company parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Company parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Company parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Company parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Company parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Company parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Company parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Company parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Company parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Company parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Company parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Company prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Company}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Company)
        CompanyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetworkEntity.internal_static_Company_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetworkEntity.internal_static_Company_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Company.class, Builder.class);
      }

      // Construct using com.maxzuo.protobuf.NetworkEntity.Company.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEmployeesFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        summary_ = "";

        type_ = 0;

        time_ = "";

        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          employeesBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetworkEntity.internal_static_Company_descriptor;
      }

      @Override
      public Company getDefaultInstanceForType() {
        return Company.getDefaultInstance();
      }

      @Override
      public Company build() {
        Company result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Company buildPartial() {
        Company result = new Company(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.summary_ = summary_;
        result.type_ = type_;
        result.time_ = time_;
        if (employeesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            employees_ = java.util.Collections.unmodifiableList(employees_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.employees_ = employees_;
        } else {
          result.employees_ = employeesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Company) {
          return mergeFrom((Company)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Company other) {
        if (other == Company.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getSummary().isEmpty()) {
          summary_ = other.summary_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (employeesBuilder_ == null) {
          if (!other.employees_.isEmpty()) {
            if (employees_.isEmpty()) {
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEmployeesIsMutable();
              employees_.addAll(other.employees_);
            }
            onChanged();
          }
        } else {
          if (!other.employees_.isEmpty()) {
            if (employeesBuilder_.isEmpty()) {
              employeesBuilder_.dispose();
              employeesBuilder_ = null;
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000001);
              employeesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEmployeesFieldBuilder() : null;
            } else {
              employeesBuilder_.addAllMessages(other.employees_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Company parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Company) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private Object summary_ = "";
      /**
       * <code>string summary = 2;</code>
       * @return The summary.
       */
      public String getSummary() {
        Object ref = summary_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          summary_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string summary = 2;</code>
       * @return The bytes for summary.
       */
      public com.google.protobuf.ByteString
          getSummaryBytes() {
        Object ref = summary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          summary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string summary = 2;</code>
       * @param value The summary to set.
       * @return This builder for chaining.
       */
      public Builder setSummary(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        summary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string summary = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSummary() {
        
        summary_ = getDefaultInstance().getSummary();
        onChanged();
        return this;
      }
      /**
       * <code>string summary = 2;</code>
       * @param value The bytes for summary to set.
       * @return This builder for chaining.
       */
      public Builder setSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        summary_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 3;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object time_ = "";
      /**
       * <code>string time = 4;</code>
       * @return The time.
       */
      public String getTime() {
        Object ref = time_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string time = 4;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 4;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>string time = 4;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Employee> employees_ =
        java.util.Collections.emptyList();
      private void ensureEmployeesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          employees_ = new java.util.ArrayList<Employee>(employees_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Employee, Employee.Builder, EmployeeOrBuilder> employeesBuilder_;

      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public java.util.List<Employee> getEmployeesList() {
        if (employeesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(employees_);
        } else {
          return employeesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public int getEmployeesCount() {
        if (employeesBuilder_ == null) {
          return employees_.size();
        } else {
          return employeesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Employee getEmployees(int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);
        } else {
          return employeesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder setEmployees(
          int index, Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.set(index, value);
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder setEmployees(
          int index, Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.set(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder addEmployees(Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder addEmployees(
          int index, Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(index, value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder addEmployees(
          Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder addEmployees(
          int index, Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder addAllEmployees(
          Iterable<? extends Employee> values) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, employees_);
          onChanged();
        } else {
          employeesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder clearEmployees() {
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          employeesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Builder removeEmployees(int index) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.remove(index);
          onChanged();
        } else {
          employeesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Employee.Builder getEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public EmployeeOrBuilder getEmployeesOrBuilder(
          int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);  } else {
          return employeesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public java.util.List<? extends EmployeeOrBuilder>
           getEmployeesOrBuilderList() {
        if (employeesBuilder_ != null) {
          return employeesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(employees_);
        }
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Employee.Builder addEmployeesBuilder() {
        return getEmployeesFieldBuilder().addBuilder(
            Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public Employee.Builder addEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().addBuilder(
            index, Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employees = 5;</code>
       */
      public java.util.List<Employee.Builder>
           getEmployeesBuilderList() {
        return getEmployeesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Employee, Employee.Builder, EmployeeOrBuilder>
          getEmployeesFieldBuilder() {
        if (employeesBuilder_ == null) {
          employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Employee, Employee.Builder, EmployeeOrBuilder>(
                  employees_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          employees_ = null;
        }
        return employeesBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Company)
    }

    // @@protoc_insertion_point(class_scope:Company)
    private static final Company DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Company();
    }

    public static Company getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Company>
        PARSER = new com.google.protobuf.AbstractParser<Company>() {
      @Override
      public Company parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Company(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Company> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Company> getParserForType() {
      return PARSER;
    }

    @Override
    public Company getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Company_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Company_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024message-entity.proto\"2\n\010Employee\022\014\n\004na" +
      "me\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\013\n\003msg\030\003 \001(\014\"`\n\007Co" +
      "mpany\022\n\n\002id\030\001 \001(\005\022\017\n\007summary\030\002 \001(\t\022\014\n\004ty" +
      "pe\030\003 \001(\005\022\014\n\004time\030\004 \001(\t\022\034\n\temployees\030\005 \003(" +
      "\0132\t.EmployeeB&\n\023com.maxzuo.protobufB\rNet" +
      "workEntityP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new String[] { "Name", "Age", "Msg", });
    internal_static_Company_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Company_descriptor,
        new String[] { "Id", "Summary", "Type", "Time", "Employees", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
