// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-invoke.proto

package com.maxzuo.grpc.protocol;

public final class NetworkProtocol {
  private NetworkProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021grpc-invoke.proto\"!\n\rSearchRequest\022\020\n\010" +
      "greeting\030\001 \001(\t\"\037\n\016SearchResponse\022\r\n\005repl" +
      "y\030\001 \001(\t2:\n\rSearchService\022)\n\006search\022\016.Sea" +
      "rchRequest\032\017.SearchResponseB-\n\030com.maxzu" +
      "o.grpc.protocolB\017NetworkProtocolP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new String[] { "Greeting", });
    internal_static_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResponse_descriptor,
        new String[] { "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
