// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-invoke.proto

package com.maxzuo.grpc.protocol;

public interface SearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   */
  String getReply();
  /**
   * <code>string reply = 1;</code>
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
