/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_maxzuo_jni_SayHello */

#ifndef _Included_com_maxzuo_jni_SayHello
#define _Included_com_maxzuo_jni_SayHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_maxzuo_jni_SayHello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_maxzuo_jni_SayHello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
